# Generated by Django 4.1.3 on 2022-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
